// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpoexpkpiqnvltcwopcn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwb2V4cGtwaXFudmx0Y3dvcGNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODc3MjUsImV4cCI6MjA3MTk2MzcyNX0.bCH8FX1KVWSu7b7FgvV9QElZ2tDdqq3GHxEgQhHCSbg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});